### ISSUE TITLE
Return value for redefined function in side-effects macro

### ISSUE THREAD

**Issue by dparis** [jaycfields/expectations#49]
The `side-effects` macro currently does not allow the caller to specify the values returned from the functions listed in `fn-vec`. After looking at the existing implementation, I added this macro to my test helpers:

```clojure
(defmacro side-effects-returning [fn-vec return-vec & forms]
  (assert-args side-effects
               (vector? fn-vec) "a vector for its fn-vec"
               (vector? return-vec) "a vector of fn-vec return values"
               (= (count return-vec)
                  (count fn-vec)) "return-vec has the same length as fn-vec")
  (let [side-effects-sym (gensym "conf-fn")]
    `(let [~side-effects-sym (atom [])]
       (with-redefs ~(vec (interleave fn-vec
                                      (map
                                       (fn [fn-return]
                                         `(fn [& args#]
                                            (swap! ~side-effects-sym conj args#)
                                            ~fn-return))
                                       return-vec)))
         ~@forms)
       @~side-effects-sym)))
```

I wound up needing this when I turned on [schema validation](https://github.com/Prismatic/schema) within an expectation for a function which called the redefined side-effect function in the tail position. Because the redefined function didn't specify a return value, it was just returning the value of the `(swap! ...)` call, which was then being returned from the function I was testing. This caused a schema validation error.

I imagine the caveats for expect vs. [expect-let](http://jayfields.com/expectations/expect-let.html) would apply here as well. That said, if you think it would be useful, feel free to use the code above however you like.

**Comment by jaycfields** [comment]
Interesting, I'd never really considered this situation, as most of the side effects I call, I'm disregarding the results. I'm going to think more on it. Thanks for the code either way, it's nice to see people using and improving expectations.

**Comment by jaycfields** [comment]
I thought a lot about this. I'm generally the type of maintainer who is happy to add functionality that I don't necessarily agree with, if it's a minimal amount of work. In this case, adding return values, or splitting the results up by fn #61 is a minimal amount of work, and I tried a few different ways to work it in.

The issue I ran into was, I don't want to break the existing behavior of `side-effects`. Thus, the only solution was adding another fn, similar to what's written above. I think it's a good fn for people that find it useful, and would be even better if it did what was asked in #61. But, I couldn't convince myself it was good to put into expectations core at the moment - for 3 reasons.

1. Adding something used only by a few people concerns me. Maintaining those types of fns almost always lead to maintenance burden via not wanting to change the api and possibly breaking it and not getting feedback that it's broken (because it's used by so few).
2. Philosophically, I think you're better off using expectations to test pure functions, and avoiding using `side-effects` and the like as much as possible. So, adding another `side-effect` specific function makes me uncomfortable.
3. Lastly, I decided against adding anything to core because it's so easy for you to add your own (as @dparis already did). If it were a hard task, I would gladly change expectations to make it easy. As a general rule, I don't think frameworks should strive to do all, but they should strive to allow people to build on them in whatever way they want. In this case, I think we're already there, as it is possible to write your own side-effect macro that does what you want.

@dparis & @muhuk, I do appreciate both of your points of view. If the general issue of 'better side effect support' is raised by more people, I will absolutely re-evaluate. Also, if you see a way for me to improve your ability to extend expectations in the way you desire, do let me know. I'm always happy to make those changes.

Thanks again. Cheers.
