### ISSUE TITLE
Exceptions thrown from binding expressions in expect-let aren't reported as errors

### ISSUE THREAD

**Issue by henriklundahl** [jaycfields/expectations#64]
Exceptions thrown from binding expressions in expect-let aren't reported as errors. Instead the test is ignored.

**Comment by henriklundahl** [comment]
[Here](https://github.com/henriklundahl/expectations-issue-64) is a minimal project that demonstrates this issue.

**Comment by jaycfields** [comment]
Thx for the bug report. I'll take a look asap. Shouldn't be too hard to fix up.

**Comment by henriklundahl** [comment]
Great! There's no rush, though, if you have better things to do...

Thanks for expectations, by the way!  :-)

**Comment by jaycfields** [comment]
A few work things to get to first, but I'll definitely take a look in the next day or so. 

Glad you're enjoying the framework.

I've actually been looking to remove expect-let, as I haven't found it useful since the addition of `more`, `more->`, and `more-of`. I don't know if I'll ever do that, but I thought it was worth mentioning.

**Comment by henriklundahl** [comment]
But those don't help in the cases where you want the same value in both the expressions that produce the actual and the expected value, do they? For example in this case:

    (expect-let [id "1PBh0M80EeSJrnQvaLoC3g"]
                id
                (uuid->b64 (b64->uuid id)))

Of course you can do...

    (let [id "1PBh0M80EeSJrnQvaLoC3g"]
      (expect id (uuid->b64 (b64->uuid id))))

...instead. This actually looks better, now that I see it. It is also a kind of workaround for this issue, because it will make `lein expectations` produce a non-zero exit code.

**Comment by magnars** [comment]
I came here to report the same issue. I'm writing integration tests with expectations as well, which would not have been possible without `expect-let`. In my case, I have to perform most of the integration test in the `let`, because the expected value contains Datomic entity ID that I don't know a priori.

**Comment by jaycfields** [comment]
I've been looking at this on and off, and I couldn't come to a good solution other than to remove expect-let. The root of the problem is expectations expects to care about only two things - the expected and the actual value. Trying to force another concept, bindings, in there really wouldn't fit without a substantial change to the core of expectations. Given that I was already headed in the direction of removing expect-let, I didn't see how making that substantial change would make sense.

@magnars I see a few options for your situation. If you'd like to post an example of a integration test, I'd be happy to take a look and see how I would change it to fit in a world where expect-let doesn't exist. If you'd rather not bother with that for the moment, you can simply define your own `expect-let`s in your code and keep (more or less) doing things as is. The code for expect-let is fairly trivial to add and maintain.

```
(defmacro expect-let [bindings e a]
  `(def ~(vary-meta (hashname &form) assoc :expectation true)
     (fn [] (let ~bindings (doexpect ~e ~a)))))
```

**Comment by jaycfields** [comment]
changelog was updated to reflect removal of expect-let and version 2.1.4 has been pushed to clojars.

**Comment by magnars** [comment]
Thanks for the offer, Jay. I'd be happy to get your input on how to do this without `expect-let`. :)

Here's a stripped down example of an integration test run with expect-let:

```clj
(expect-let [storage (create-in-memory-datomic (datomic.api/squuid))

             result (update-player storage nil [[:changed :current-room 19]])
             player-id (:player-id result)
             player-0 (get-newest-player storage player-id)

             _ (update-player storage player-id [[:changed :name "John" :was nil]])
             player-1 (get-newest-player storage player-id)

             _ (update-player storage player-id [[:changed :current-room 21 :was 19]])
             player-2 (get-newest-player storage player-id)]

            {:player-0 {:id player-id
                        :name nil
                        :current-room 19}

             :player-1 {:id player-id
                        :name "John"
                        :current-room 19}

             :player-2 {:id player-id
                        :name "John"
                        :current-room 21}}
            {:player-0 player-0
             :player-1 player-1
             :player-2 player-2})
```

As you can see, `player-id` is generated by the actual, but also needed by the expected.

**Comment by jaycfields** [comment]
I'd solve this in 1 of the 3 following ways, I believe.

solution 1: The id is generated, so testing it doesn't provide much value; test the other values
```clj
(expect
  {:player-0 {:name nil :current-room 19}
   :player-1 {:name "John" :current-room 19}
   :player-2 {:name "John" :current-room 21}}
  (in
   (let [storage (create-in-memory-datomic (datomic.api/squuid))

         result (update-player storage nil [[:changed :current-room 19]])
         player-id (:player-id result)
         player-0 (get-newest-player storage player-id)

         _ (update-player storage player-id [[:changed :name "John" :was nil]])
         player-1 (get-newest-player storage player-id)

         _ (update-player storage player-id [[:changed :current-room 21 :was 19]])
         player-2 (get-newest-player storage player-id)])
   {:player-0 player-0
    :player-1 player-1
    :player-2 player-2}))
```
solution 2 is to use more-> to dissoc :player-id
```clj
(expect
  (more->
   {:name nil :current-room 19} (-> :player-0 (dissoc :player-id))
   {:name "John" :current-room 19} (-> :player-1 (dissoc :player-id))
   {:name "John" :current-room 21} (-> :player-2 (dissoc :player-id)))
  (in
   (let [storage (create-in-memory-datomic (datomic.api/squuid))

         result (update-player storage nil [[:changed :current-room 19]])
         player-id (:player-id result)
         player-0 (get-newest-player storage player-id)

         _ (update-player storage player-id [[:changed :name "John" :was nil]])
         player-1 (get-newest-player storage player-id)

         _ (update-player storage player-id [[:changed :current-room 21 :was 19]])
         player-2 (get-newest-player storage player-id)])
   {:player-0 player-0
    :player-1 player-1
    :player-2 player-2}))
```
Of course, you could just dissoc in the expected value also.

Solution 3 is to pass result through as well.
```clj
(expect
  (more-of [player-id players]
           true? (apply = player-id (->> players vals (map :player-id)))
           {:name nil :current-room 19} (in (:player-0 players))
           {:name "John" :current-room 19} (in (:player-1 players))
           {:name "John" :current-room 21} (in (:player-2 players)))
  (in
   (let [storage (create-in-memory-datomic (datomic.api/squuid))

         result (update-player storage nil [[:changed :current-room 19]])
         player-id (:player-id result)
         player-0 (get-newest-player storage player-id)

         _ (update-player storage player-id [[:changed :name "John" :was nil]])
         player-1 (get-newest-player storage player-id)

         _ (update-player storage player-id [[:changed :current-room 21 :was 19]])
         player-2 (get-newest-player storage player-id)])
   [player-id
    {:player-0 player-0
     :player-1 player-1
     :player-2 player-2}]))
```

**Comment by magnars** [comment]
Thanks for the suggestions, Jay! I'll try these out and see which fits best. :)
